/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, {Component} from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

type Props = {};
export default class App extends Component<Props> {
    render() {
        return (
            <View style={styles.container}>
                <ScrollView>
                    <View style={{ backgroundColor: 'white', padding: 12, margin: 20, borderRadius: 8 }}>
                        <Text>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam non enim dolor. Nulla facilisi. Cras imperdiet tortor vehicula pulvinar volutpat. Donec tellus diam, convallis id erat sagittis, porttitor elementum urna. Phasellus posuere dapibus mi, non mollis ex pharetra nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce eget lobortis libero. Mauris eu sapien magna. Morbi sit amet vulputate augue. Nam non magna ipsum. Vivamus pretium nulla vel arcu lacinia, sit amet tincidunt elit congue. Nunc sed placerat tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec nec venenatis ante. Proin dignissim in tellus nec commodo.

                            Morbi volutpat orci in ex faucibus, vitae congue ante porta. Nam ut libero justo. Sed sed elementum metus. Ut sagittis suscipit justo, consequat varius tellus malesuada quis. Nullam tincidunt orci at auctor lobortis. Proin congue lorem vel ligula malesuada vestibulum. Sed est elit, dignissim id neque sit amet, semper laoreet lorem. Phasellus lobortis aliquam lorem, rhoncus molestie risus bibendum quis. Mauris ultricies elit quam.

                            Aliquam rhoncus, ligula vel faucibus suscipit, ligula magna feugiat sapien, non ullamcorper turpis nunc nec magna. Nulla facilisi. Aenean condimentum bibendum lorem in pharetra. Nullam orci mauris, tempus id bibendum in, blandit non urna. Cras condimentum sit amet turpis a volutpat. Sed tempus erat elit, sed mattis neque cursus nec. Integer at lacus sed felis egestas congue. Suspendisse consectetur lacinia erat sed sollicitudin. Curabitur quis risus vehicula, venenatis risus ut, venenatis erat. Sed semper laoreet ipsum, et bibendum tellus pulvinar eget. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer fringilla nulla sed ante aliquam, eget congue mi pulvinar. Sed eu purus aliquam, lobortis nisi nec, ultrices nisi. Nam erat mauris, commodo et ligula eu, lobortis efficitur arcu.

                            Donec non ultrices dolor. Ut dolor est, ornare sit amet laoreet ac, ultrices rhoncus turpis. Nulla in mattis diam. Nullam ac aliquam nunc. Phasellus libero dolor, dapibus quis tempor sit amet, varius ac arcu. Aliquam porta condimentum ultricies. Nulla sit amet nisl nec enim consectetur pretium. Aliquam tincidunt nulla lorem, eget maximus diam interdum et. Vivamus dapibus justo quis egestas porta. Proin porta magna ac efficitur semper. Donec nec ante purus. Etiam vel risus magna. Nunc laoreet sem id facilisis eleifend. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi eu tempus quam, vel tincidunt elit.

                            Vestibulum vestibulum nisl eu tortor pretium auctor. Praesent condimentum rhoncus nisl, quis maximus lacus interdum et. Curabitur eleifend fringilla lectus, quis rutrum dolor. Vivamus nec consectetur libero. Mauris ac finibus nunc. Nunc ullamcorper, ex non ornare tincidunt, augue nulla lobortis orci, eu auctor purus ipsum non mi. Duis consectetur vehicula quam a tempus. Pellentesque imperdiet, elit a imperdiet dignissim, orci tellus imperdiet eros, vitae cursus nulla nibh a dui. Maecenas nunc felis, condimentum non elit id, bibendum molestie sem. Sed eros massa, posuere a enim nec, lacinia auctor urna. Pellentesque posuere semper est, vitae consectetur est mollis non. Suspendisse potenti. Aliquam ut consectetur dui. Integer nec risus lacinia, tempus velit blandit, venenatis tellus.

                            Morbi et magna ac risus condimentum vulputate. Suspendisse accumsan mauris at vehicula tincidunt. Maecenas quam tortor, porta id neque eu, consectetur sodales sapien. Mauris ac ipsum est. Phasellus nulla elit, accumsan dignissim lorem sed, venenatis tincidunt ante. Etiam justo augue, condimentum et dictum rutrum, blandit ut diam. Quisque vitae imperdiet nunc. Duis quis feugiat nunc, tempus efficitur tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi tempor semper scelerisque. Mauris non tincidunt felis, at cursus lorem. Donec ultrices neque eu sapien rutrum, eu ullamcorper dolor interdum. Praesent non enim eu est bibendum pretium quis et tellus. Nullam nec ipsum libero. Suspendisse eu blandit elit.

                            Morbi vel condimentum metus. Duis egestas laoreet leo eu vehicula. Ut volutpat aliquet nulla. Vestibulum in orci scelerisque, pulvinar quam non, elementum nunc. Nam eleifend tincidunt ligula. Nunc maximus pulvinar auctor. Pellentesque pharetra condimentum lorem, non laoreet ligula sodales vel. Nam aliquam non tortor vitae blandit. Phasellus interdum sed ligula a congue. Nulla facilisi. Donec dignissim lectus quis leo euismod vulputate. Mauris ullamcorper nibh vel dolor mollis, tincidunt consequat leo porttitor. Phasellus semper venenatis felis, vel tincidunt metus lacinia id. Integer finibus purus ligula, non sodales dui hendrerit ut. Integer facilisis arcu dui, eu congue ligula consequat nec. Nam congue metus a dignissim luctus.

                            Proin vitae justo mauris. Ut venenatis interdum magna id hendrerit. Etiam tincidunt erat augue, at dictum quam viverra at. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque id ligula varius, auctor lectus dapibus, facilisis erat. Nulla vehicula urna sed metus volutpat ornare. Fusce congue vehicula placerat. Aliquam finibus, arcu eget porta finibus, nisl urna hendrerit justo, in scelerisque est nisi vel ipsum. Sed sodales condimentum sagittis. Suspendisse potenti. Etiam arcu neque, vehicula nec massa sed, rutrum vulputate risus. Donec commodo nulla tristique elit facilisis, in volutpat lorem suscipit.

                            Donec facilisis neque sit amet libero pharetra, vitae aliquam dui elementum. Quisque condimentum sit amet sapien sit amet pretium. Vestibulum rhoncus massa sed consequat egestas. Nam suscipit semper sagittis. Nam vehicula justo nisl, sit amet cursus dui egestas eget. Proin sollicitudin sed nulla sed varius. Sed condimentum tempus urna, non commodo mauris vulputate et. Maecenas laoreet aliquam magna, rhoncus egestas erat pretium vitae. Nullam sit amet efficitur augue. Morbi vehicula felis ut ex mattis congue. Donec euismod viverra tristique. Ut erat sapien, sollicitudin quis venenatis eu, molestie vitae justo. Suspendisse vitae hendrerit est.

                            Pellentesque sodales est sed dignissim convallis. Duis iaculis vestibulum euismod. Fusce finibus dapibus ultrices. Maecenas maximus erat ac ipsum molestie, vel volutpat arcu tempus. Duis laoreet convallis turpis ut condimentum. Pellentesque gravida, velit ut pharetra mattis, ex odio volutpat dolor, eu condimentum diam metus a diam. Sed ut venenatis mi, sed egestas turpis. Phasellus et purus massa. Nullam felis nulla, feugiat vitae magna at, ullamcorper dignissim lorem. Fusce et sapien tempus, tincidunt libero vitae, pellentesque turpis. Vivamus congue consequat hendrerit. Maecenas sed posuere neque, quis pharetra nibh. Sed aliquet posuere sapien. Maecenas libero eros, tempor in velit sed, dignissim feugiat mauris.

                            Curabitur varius ornare fermentum. Mauris bibendum eu ex at faucibus. Proin a lacus dolor. Fusce enim justo, blandit ac tempor et, rutrum vel ligula. Donec mollis vitae dolor ut elementum. Nunc urna ipsum, dictum at efficitur non, consequat vitae nisi. Praesent at metus luctus, convallis tellus eget, finibus sapien. Fusce eleifend eget elit et euismod. Nam ac porta nibh. Sed nec molestie ex. Nulla facilisi.

                            Proin nec ipsum eu felis hendrerit tincidunt id sed nulla. Quisque pharetra tincidunt laoreet. In hac habitasse platea dictumst. Cras nec iaculis libero. Suspendisse molestie, orci quis iaculis pulvinar, velit dui fermentum est, vel egestas quam libero nec neque. Proin ut nisl id tellus fringilla porttitor. Mauris vehicula dapibus sem, ac sodales augue vulputate vitae. Ut at libero cursus, hendrerit erat in, iaculis enim.

                            Nulla sed sodales erat, at egestas neque. Ut ut orci quis sem pulvinar convallis. Mauris in leo nec enim dignissim facilisis sit amet id elit. Nulla scelerisque felis finibus risus maximus, nec accumsan justo viverra. In finibus rhoncus vehicula. Vestibulum et sem magna. Vivamus vehicula urna id justo luctus tempus.

                            Donec tincidunt lobortis augue ut posuere. Nam neque odio, rhoncus ac fermentum nec, luctus eu dui. Aenean malesuada risus at nibh accumsan, quis auctor ipsum tempor. Donec felis justo, congue eget fringilla nec, faucibus porta justo. Nullam laoreet elit vitae dolor pharetra vulputate. Vestibulum dictum sit amet mi sed aliquet. Vivamus lacinia nulla sit amet dolor facilisis, ut maximus mauris bibendum. Proin mollis turpis quis tellus mattis, quis sollicitudin lacus egestas. Aenean quam lacus, dapibus dictum gravida tempus, luctus pellentesque lacus. Phasellus rhoncus pulvinar eros vel pharetra. Fusce porta blandit ornare. Donec diam ligula, rutrum et enim quis, consectetur pharetra risus. Mauris dapibus nisl in vehicula molestie. Mauris id vehicula mauris. Nulla sem lacus, pharetra id ex et, auctor laoreet nunc.

                            Quisque bibendum felis nisi, sit amet cursus turpis faucibus sit amet. Curabitur vulputate rutrum vehicula. Nunc turpis ipsum, aliquam in laoreet vitae, fringilla eget neque. Vestibulum eu sodales est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque in feugiat ipsum. Aliquam mollis urna sit amet nibh maximus, non cursus elit viverra. Aenean at arcu tincidunt, tempor lorem eget, consequat nisi. Suspendisse porta ante sit amet magna sagittis, eu mollis orci lacinia. Mauris a augue eget tellus molestie convallis.

                            Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent eget lacus at metus cursus fringilla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed euismod viverra mollis. Aliquam facilisis semper nibh non ultrices. Praesent eleifend neque turpis, eget ultrices erat feugiat at. Vestibulum nec arcu at turpis laoreet lacinia. Morbi purus enim, sagittis quis pharetra ultrices, accumsan quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean eget sapien risus. Sed volutpat, dui sit amet rutrum placerat, neque elit volutpat justo, id lacinia elit erat vitae massa. Pellentesque finibus pretium nulla ac mattis. Morbi molestie a purus sit amet pretium. Suspendisse hendrerit tincidunt ante, quis dictum felis lacinia ac. Praesent tempor urna tellus.

                            Sed sit amet venenatis quam. Nam vestibulum, tortor eget luctus condimentum, lorem tortor cursus massa, non bibendum massa ligula et mauris. Cras at arcu mattis lectus euismod imperdiet ac eu nisi. Etiam malesuada sem nibh, quis elementum nulla tincidunt sed. Nam elementum purus sit amet convallis faucibus. Praesent et velit ac sapien facilisis consequat. Mauris non facilisis mi. Sed lobortis lorem vitae turpis efficitur iaculis. Curabitur id est ac tellus sodales sagittis. Donec vehicula nisi est, ultrices malesuada lacus consequat ut.

                            Nam eu consectetur dolor. Sed pretium ut nulla sed congue. Proin convallis enim metus, vitae sagittis tortor tristique sit amet. Duis sit amet viverra massa, quis ultricies tortor. Aliquam eu dui congue, semper massa sed, feugiat metus. Mauris est nisi, finibus sit amet arcu id, laoreet semper ante. Etiam quis sodales ipsum. Donec sed porta erat. Nullam ac lectus arcu. Suspendisse sem tellus, suscipit ut accumsan vel, dictum vitae nulla. Phasellus fringilla dui aliquam egestas varius. Nunc at neque nunc. Nullam ac eros ornare, laoreet massa eu, porta erat.

                            Fusce eget dolor id velit venenatis varius. Integer velit mauris, luctus eu vehicula eget, congue et diam. Praesent eu luctus lectus, ac congue tortor. Nullam lacinia sapien eget orci lobortis, quis rhoncus ex finibus. Etiam maximus odio sit amet nibh semper hendrerit. Nulla sed pharetra mi. Mauris leo dolor, pulvinar ac tempus vel, semper nec quam. Etiam volutpat lectus vel nunc fermentum, ut tempor erat luctus. Nunc euismod orci nec leo consequat placerat. Praesent suscipit consectetur dolor, in blandit dolor placerat vel.

                            Maecenas posuere libero non molestie lobortis. Sed ut mattis lorem. Donec euismod leo vitae turpis porttitor, id pulvinar tortor imperdiet. Quisque nec felis eu est scelerisque maximus sit amet sed augue. Nam non convallis odio. Donec id lacus non eros ullamcorper rhoncus nec eget lacus. Suspendisse potenti. Curabitur quam velit, finibus eu rutrum ut, tincidunt a leo. Morbi a finibus eros, eu tincidunt enim. Mauris tincidunt euismod leo vitae tincidunt. Sed fringilla, urna sit amet varius malesuada, sapien turpis vestibulum elit, quis sagittis tellus ex at dolor.

                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam non enim dolor. Nulla facilisi. Cras imperdiet tortor vehicula pulvinar volutpat. Donec tellus diam, convallis id erat sagittis, porttitor elementum urna. Phasellus posuere dapibus mi, non mollis ex pharetra nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce eget lobortis libero. Mauris eu sapien magna. Morbi sit amet vulputate augue. Nam non magna ipsum. Vivamus pretium nulla vel arcu lacinia, sit amet tincidunt elit congue. Nunc sed placerat tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec nec venenatis ante. Proin dignissim in tellus nec commodo.

                            Morbi volutpat orci in ex faucibus, vitae congue ante porta. Nam ut libero justo. Sed sed elementum metus. Ut sagittis suscipit justo, consequat varius tellus malesuada quis. Nullam tincidunt orci at auctor lobortis. Proin congue lorem vel ligula malesuada vestibulum. Sed est elit, dignissim id neque sit amet, semper laoreet lorem. Phasellus lobortis aliquam lorem, rhoncus molestie risus bibendum quis. Mauris ultricies elit quam.

                            Aliquam rhoncus, ligula vel faucibus suscipit, ligula magna feugiat sapien, non ullamcorper turpis nunc nec magna. Nulla facilisi. Aenean condimentum bibendum lorem in pharetra. Nullam orci mauris, tempus id bibendum in, blandit non urna. Cras condimentum sit amet turpis a volutpat. Sed tempus erat elit, sed mattis neque cursus nec. Integer at lacus sed felis egestas congue. Suspendisse consectetur lacinia erat sed sollicitudin. Curabitur quis risus vehicula, venenatis risus ut, venenatis erat. Sed semper laoreet ipsum, et bibendum tellus pulvinar eget. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer fringilla nulla sed ante aliquam, eget congue mi pulvinar. Sed eu purus aliquam, lobortis nisi nec, ultrices nisi. Nam erat mauris, commodo et ligula eu, lobortis efficitur arcu.

                            Donec non ultrices dolor. Ut dolor est, ornare sit amet laoreet ac, ultrices rhoncus turpis. Nulla in mattis diam. Nullam ac aliquam nunc. Phasellus libero dolor, dapibus quis tempor sit amet, varius ac arcu. Aliquam porta condimentum ultricies. Nulla sit amet nisl nec enim consectetur pretium. Aliquam tincidunt nulla lorem, eget maximus diam interdum et. Vivamus dapibus justo quis egestas porta. Proin porta magna ac efficitur semper. Donec nec ante purus. Etiam vel risus magna. Nunc laoreet sem id facilisis eleifend. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi eu tempus quam, vel tincidunt elit.

                            Vestibulum vestibulum nisl eu tortor pretium auctor. Praesent condimentum rhoncus nisl, quis maximus lacus interdum et. Curabitur eleifend fringilla lectus, quis rutrum dolor. Vivamus nec consectetur libero. Mauris ac finibus nunc. Nunc ullamcorper, ex non ornare tincidunt, augue nulla lobortis orci, eu auctor purus ipsum non mi. Duis consectetur vehicula quam a tempus. Pellentesque imperdiet, elit a imperdiet dignissim, orci tellus imperdiet eros, vitae cursus nulla nibh a dui. Maecenas nunc felis, condimentum non elit id, bibendum molestie sem. Sed eros massa, posuere a enim nec, lacinia auctor urna. Pellentesque posuere semper est, vitae consectetur est mollis non. Suspendisse potenti. Aliquam ut consectetur dui. Integer nec risus lacinia, tempus velit blandit, venenatis tellus.

                            Morbi et magna ac risus condimentum vulputate. Suspendisse accumsan mauris at vehicula tincidunt. Maecenas quam tortor, porta id neque eu, consectetur sodales sapien. Mauris ac ipsum est. Phasellus nulla elit, accumsan dignissim lorem sed, venenatis tincidunt ante. Etiam justo augue, condimentum et dictum rutrum, blandit ut diam. Quisque vitae imperdiet nunc. Duis quis feugiat nunc, tempus efficitur tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi tempor semper scelerisque. Mauris non tincidunt felis, at cursus lorem. Donec ultrices neque eu sapien rutrum, eu ullamcorper dolor interdum. Praesent non enim eu est bibendum pretium quis et tellus. Nullam nec ipsum libero. Suspendisse eu blandit elit.

                            Morbi vel condimentum metus. Duis egestas laoreet leo eu vehicula. Ut volutpat aliquet nulla. Vestibulum in orci scelerisque, pulvinar quam non, elementum nunc. Nam eleifend tincidunt ligula. Nunc maximus pulvinar auctor. Pellentesque pharetra condimentum lorem, non laoreet ligula sodales vel. Nam aliquam non tortor vitae blandit. Phasellus interdum sed ligula a congue. Nulla facilisi. Donec dignissim lectus quis leo euismod vulputate. Mauris ullamcorper nibh vel dolor mollis, tincidunt consequat leo porttitor. Phasellus semper venenatis felis, vel tincidunt metus lacinia id. Integer finibus purus ligula, non sodales dui hendrerit ut. Integer facilisis arcu dui, eu congue ligula consequat nec. Nam congue metus a dignissim luctus.

                            Proin vitae justo mauris. Ut venenatis interdum magna id hendrerit. Etiam tincidunt erat augue, at dictum quam viverra at. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque id ligula varius, auctor lectus dapibus, facilisis erat. Nulla vehicula urna sed metus volutpat ornare. Fusce congue vehicula placerat. Aliquam finibus, arcu eget porta finibus, nisl urna hendrerit justo, in scelerisque est nisi vel ipsum. Sed sodales condimentum sagittis. Suspendisse potenti. Etiam arcu neque, vehicula nec massa sed, rutrum vulputate risus. Donec commodo nulla tristique elit facilisis, in volutpat lorem suscipit.

                            Donec facilisis neque sit amet libero pharetra, vitae aliquam dui elementum. Quisque condimentum sit amet sapien sit amet pretium. Vestibulum rhoncus massa sed consequat egestas. Nam suscipit semper sagittis. Nam vehicula justo nisl, sit amet cursus dui egestas eget. Proin sollicitudin sed nulla sed varius. Sed condimentum tempus urna, non commodo mauris vulputate et. Maecenas laoreet aliquam magna, rhoncus egestas erat pretium vitae. Nullam sit amet efficitur augue. Morbi vehicula felis ut ex mattis congue. Donec euismod viverra tristique. Ut erat sapien, sollicitudin quis venenatis eu, molestie vitae justo. Suspendisse vitae hendrerit est.

                            Pellentesque sodales est sed dignissim convallis. Duis iaculis vestibulum euismod. Fusce finibus dapibus ultrices. Maecenas maximus erat ac ipsum molestie, vel volutpat arcu tempus. Duis laoreet convallis turpis ut condimentum. Pellentesque gravida, velit ut pharetra mattis, ex odio volutpat dolor, eu condimentum diam metus a diam. Sed ut venenatis mi, sed egestas turpis. Phasellus et purus massa. Nullam felis nulla, feugiat vitae magna at, ullamcorper dignissim lorem. Fusce et sapien tempus, tincidunt libero vitae, pellentesque turpis. Vivamus congue consequat hendrerit. Maecenas sed posuere neque, quis pharetra nibh. Sed aliquet posuere sapien. Maecenas libero eros, tempor in velit sed, dignissim feugiat mauris.

                            Curabitur varius ornare fermentum. Mauris bibendum eu ex at faucibus. Proin a lacus dolor. Fusce enim justo, blandit ac tempor et, rutrum vel ligula. Donec mollis vitae dolor ut elementum. Nunc urna ipsum, dictum at efficitur non, consequat vitae nisi. Praesent at metus luctus, convallis tellus eget, finibus sapien. Fusce eleifend eget elit et euismod. Nam ac porta nibh. Sed nec molestie ex. Nulla facilisi.

                            Proin nec ipsum eu felis hendrerit tincidunt id sed nulla. Quisque pharetra tincidunt laoreet. In hac habitasse platea dictumst. Cras nec iaculis libero. Suspendisse molestie, orci quis iaculis pulvinar, velit dui fermentum est, vel egestas quam libero nec neque. Proin ut nisl id tellus fringilla porttitor. Mauris vehicula dapibus sem, ac sodales augue vulputate vitae. Ut at libero cursus, hendrerit erat in, iaculis enim.

                            Nulla sed sodales erat, at egestas neque. Ut ut orci quis sem pulvinar convallis. Mauris in leo nec enim dignissim facilisis sit amet id elit. Nulla scelerisque felis finibus risus maximus, nec accumsan justo viverra. In finibus rhoncus vehicula. Vestibulum et sem magna. Vivamus vehicula urna id justo luctus tempus.

                            Donec tincidunt lobortis augue ut posuere. Nam neque odio, rhoncus ac fermentum nec, luctus eu dui. Aenean malesuada risus at nibh accumsan, quis auctor ipsum tempor. Donec felis justo, congue eget fringilla nec, faucibus porta justo. Nullam laoreet elit vitae dolor pharetra vulputate. Vestibulum dictum sit amet mi sed aliquet. Vivamus lacinia nulla sit amet dolor facilisis, ut maximus mauris bibendum. Proin mollis turpis quis tellus mattis, quis sollicitudin lacus egestas. Aenean quam lacus, dapibus dictum gravida tempus, luctus pellentesque lacus. Phasellus rhoncus pulvinar eros vel pharetra. Fusce porta blandit ornare. Donec diam ligula, rutrum et enim quis, consectetur pharetra risus. Mauris dapibus nisl in vehicula molestie. Mauris id vehicula mauris. Nulla sem lacus, pharetra id ex et, auctor laoreet nunc.

                            Quisque bibendum felis nisi, sit amet cursus turpis faucibus sit amet. Curabitur vulputate rutrum vehicula. Nunc turpis ipsum, aliquam in laoreet vitae, fringilla eget neque. Vestibulum eu sodales est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque in feugiat ipsum. Aliquam mollis urna sit amet nibh maximus, non cursus elit viverra. Aenean at arcu tincidunt, tempor lorem eget, consequat nisi. Suspendisse porta ante sit amet magna sagittis, eu mollis orci lacinia. Mauris a augue eget tellus molestie convallis.

                            Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent eget lacus at metus cursus fringilla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed euismod viverra mollis. Aliquam facilisis semper nibh non ultrices. Praesent eleifend neque turpis, eget ultrices erat feugiat at. Vestibulum nec arcu at turpis laoreet lacinia. Morbi purus enim, sagittis quis pharetra ultrices, accumsan quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean eget sapien risus. Sed volutpat, dui sit amet rutrum placerat, neque elit volutpat justo, id lacinia elit erat vitae massa. Pellentesque finibus pretium nulla ac mattis. Morbi molestie a purus sit amet pretium. Suspendisse hendrerit tincidunt ante, quis dictum felis lacinia ac. Praesent tempor urna tellus.

                            Sed sit amet venenatis quam. Nam vestibulum, tortor eget luctus condimentum, lorem tortor cursus massa, non bibendum massa ligula et mauris. Cras at arcu mattis lectus euismod imperdiet ac eu nisi. Etiam malesuada sem nibh, quis elementum nulla tincidunt sed. Nam elementum purus sit amet convallis faucibus. Praesent et velit ac sapien facilisis consequat. Mauris non facilisis mi. Sed lobortis lorem vitae turpis efficitur iaculis. Curabitur id est ac tellus sodales sagittis. Donec vehicula nisi est, ultrices malesuada lacus consequat ut.

                            Nam eu consectetur dolor. Sed pretium ut nulla sed congue. Proin convallis enim metus, vitae sagittis tortor tristique sit amet. Duis sit amet viverra massa, quis ultricies tortor. Aliquam eu dui congue, semper massa sed, feugiat metus. Mauris est nisi, finibus sit amet arcu id, laoreet semper ante. Etiam quis sodales ipsum. Donec sed porta erat. Nullam ac lectus arcu. Suspendisse sem tellus, suscipit ut accumsan vel, dictum vitae nulla. Phasellus fringilla dui aliquam egestas varius. Nunc at neque nunc. Nullam ac eros ornare, laoreet massa eu, porta erat.

                            Fusce eget dolor id velit venenatis varius. Integer velit mauris, luctus eu vehicula eget, congue et diam. Praesent eu luctus lectus, ac congue tortor. Nullam lacinia sapien eget orci lobortis, quis rhoncus ex finibus. Etiam maximus odio sit amet nibh semper hendrerit. Nulla sed pharetra mi. Mauris leo dolor, pulvinar ac tempus vel, semper nec quam. Etiam volutpat lectus vel nunc fermentum, ut tempor erat luctus. Nunc euismod orci nec leo consequat placerat. Praesent suscipit consectetur dolor, in blandit dolor placerat vel.

                            Maecenas posuere libero non molestie lobortis. Sed ut mattis lorem. Donec euismod leo vitae turpis porttitor, id pulvinar tortor imperdiet. Quisque nec felis eu est scelerisque maximus sit amet sed augue. Nam non convallis odio. Donec id lacus non eros ullamcorper rhoncus nec eget lacus. Suspendisse potenti. Curabitur quam velit, finibus eu rutrum ut, tincidunt a leo. Morbi a finibus eros, eu tincidunt enim. Mauris tincidunt euismod leo vitae tincidunt. Sed fringilla, urna sit amet varius malesuada, sapien turpis vestibulum elit, quis sagittis tellus ex at dolor.

                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam non enim dolor. Nulla facilisi. Cras imperdiet tortor vehicula pulvinar volutpat. Donec tellus diam, convallis id erat sagittis, porttitor elementum urna. Phasellus posuere dapibus mi, non mollis ex pharetra nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce eget lobortis libero. Mauris eu sapien magna. Morbi sit amet vulputate augue. Nam non magna ipsum. Vivamus pretium nulla vel arcu lacinia, sit amet tincidunt elit congue. Nunc sed placerat tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec nec venenatis ante. Proin dignissim in tellus nec commodo.

                            Morbi volutpat orci in ex faucibus, vitae congue ante porta. Nam ut libero justo. Sed sed elementum metus. Ut sagittis suscipit justo, consequat varius tellus malesuada quis. Nullam tincidunt orci at auctor lobortis. Proin congue lorem vel ligula malesuada vestibulum. Sed est elit, dignissim id neque sit amet, semper laoreet lorem. Phasellus lobortis aliquam lorem, rhoncus molestie risus bibendum quis. Mauris ultricies elit quam.

                            Aliquam rhoncus, ligula vel faucibus suscipit, ligula magna feugiat sapien, non ullamcorper turpis nunc nec magna. Nulla facilisi. Aenean condimentum bibendum lorem in pharetra. Nullam orci mauris, tempus id bibendum in, blandit non urna. Cras condimentum sit amet turpis a volutpat. Sed tempus erat elit, sed mattis neque cursus nec. Integer at lacus sed felis egestas congue. Suspendisse consectetur lacinia erat sed sollicitudin. Curabitur quis risus vehicula, venenatis risus ut, venenatis erat. Sed semper laoreet ipsum, et bibendum tellus pulvinar eget. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer fringilla nulla sed ante aliquam, eget congue mi pulvinar. Sed eu purus aliquam, lobortis nisi nec, ultrices nisi. Nam erat mauris, commodo et ligula eu, lobortis efficitur arcu.

                            Donec non ultrices dolor. Ut dolor est, ornare sit amet laoreet ac, ultrices rhoncus turpis. Nulla in mattis diam. Nullam ac aliquam nunc. Phasellus libero dolor, dapibus quis tempor sit amet, varius ac arcu. Aliquam porta condimentum ultricies. Nulla sit amet nisl nec enim consectetur pretium. Aliquam tincidunt nulla lorem, eget maximus diam interdum et. Vivamus dapibus justo quis egestas porta. Proin porta magna ac efficitur semper. Donec nec ante purus. Etiam vel risus magna. Nunc laoreet sem id facilisis eleifend. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi eu tempus quam, vel tincidunt elit.

                            Vestibulum vestibulum nisl eu tortor pretium auctor. Praesent condimentum rhoncus nisl, quis maximus lacus interdum et. Curabitur eleifend fringilla lectus, quis rutrum dolor. Vivamus nec consectetur libero. Mauris ac finibus nunc. Nunc ullamcorper, ex non ornare tincidunt, augue nulla lobortis orci, eu auctor purus ipsum non mi. Duis consectetur vehicula quam a tempus. Pellentesque imperdiet, elit a imperdiet dignissim, orci tellus imperdiet eros, vitae cursus nulla nibh a dui. Maecenas nunc felis, condimentum non elit id, bibendum molestie sem. Sed eros massa, posuere a enim nec, lacinia auctor urna. Pellentesque posuere semper est, vitae consectetur est mollis non. Suspendisse potenti. Aliquam ut consectetur dui. Integer nec risus lacinia, tempus velit blandit, venenatis tellus.

                            Morbi et magna ac risus condimentum vulputate. Suspendisse accumsan mauris at vehicula tincidunt. Maecenas quam tortor, porta id neque eu, consectetur sodales sapien. Mauris ac ipsum est. Phasellus nulla elit, accumsan dignissim lorem sed, venenatis tincidunt ante. Etiam justo augue, condimentum et dictum rutrum, blandit ut diam. Quisque vitae imperdiet nunc. Duis quis feugiat nunc, tempus efficitur tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi tempor semper scelerisque. Mauris non tincidunt felis, at cursus lorem. Donec ultrices neque eu sapien rutrum, eu ullamcorper dolor interdum. Praesent non enim eu est bibendum pretium quis et tellus. Nullam nec ipsum libero. Suspendisse eu blandit elit.

                            Morbi vel condimentum metus. Duis egestas laoreet leo eu vehicula. Ut volutpat aliquet nulla. Vestibulum in orci scelerisque, pulvinar quam non, elementum nunc. Nam eleifend tincidunt ligula. Nunc maximus pulvinar auctor. Pellentesque pharetra condimentum lorem, non laoreet ligula sodales vel. Nam aliquam non tortor vitae blandit. Phasellus interdum sed ligula a congue. Nulla facilisi. Donec dignissim lectus quis leo euismod vulputate. Mauris ullamcorper nibh vel dolor mollis, tincidunt consequat leo porttitor. Phasellus semper venenatis felis, vel tincidunt metus lacinia id. Integer finibus purus ligula, non sodales dui hendrerit ut. Integer facilisis arcu dui, eu congue ligula consequat nec. Nam congue metus a dignissim luctus.

                            Proin vitae justo mauris. Ut venenatis interdum magna id hendrerit. Etiam tincidunt erat augue, at dictum quam viverra at. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque id ligula varius, auctor lectus dapibus, facilisis erat. Nulla vehicula urna sed metus volutpat ornare. Fusce congue vehicula placerat. Aliquam finibus, arcu eget porta finibus, nisl urna hendrerit justo, in scelerisque est nisi vel ipsum. Sed sodales condimentum sagittis. Suspendisse potenti. Etiam arcu neque, vehicula nec massa sed, rutrum vulputate risus. Donec commodo nulla tristique elit facilisis, in volutpat lorem suscipit.

                            Donec facilisis neque sit amet libero pharetra, vitae aliquam dui elementum. Quisque condimentum sit amet sapien sit amet pretium. Vestibulum rhoncus massa sed consequat egestas. Nam suscipit semper sagittis. Nam vehicula justo nisl, sit amet cursus dui egestas eget. Proin sollicitudin sed nulla sed varius. Sed condimentum tempus urna, non commodo mauris vulputate et. Maecenas laoreet aliquam magna, rhoncus egestas erat pretium vitae. Nullam sit amet efficitur augue. Morbi vehicula felis ut ex mattis congue. Donec euismod viverra tristique. Ut erat sapien, sollicitudin quis venenatis eu, molestie vitae justo. Suspendisse vitae hendrerit est.

                            Pellentesque sodales est sed dignissim convallis. Duis iaculis vestibulum euismod. Fusce finibus dapibus ultrices. Maecenas maximus erat ac ipsum molestie, vel volutpat arcu tempus. Duis laoreet convallis turpis ut condimentum. Pellentesque gravida, velit ut pharetra mattis, ex odio volutpat dolor, eu condimentum diam metus a diam. Sed ut venenatis mi, sed egestas turpis. Phasellus et purus massa. Nullam felis nulla, feugiat vitae magna at, ullamcorper dignissim lorem. Fusce et sapien tempus, tincidunt libero vitae, pellentesque turpis. Vivamus congue consequat hendrerit. Maecenas sed posuere neque, quis pharetra nibh. Sed aliquet posuere sapien. Maecenas libero eros, tempor in velit sed, dignissim feugiat mauris.

                            Curabitur varius ornare fermentum. Mauris bibendum eu ex at faucibus. Proin a lacus dolor. Fusce enim justo, blandit ac tempor et, rutrum vel ligula. Donec mollis vitae dolor ut elementum. Nunc urna ipsum, dictum at efficitur non, consequat vitae nisi. Praesent at metus luctus, convallis tellus eget, finibus sapien. Fusce eleifend eget elit et euismod. Nam ac porta nibh. Sed nec molestie ex. Nulla facilisi.

                            Proin nec ipsum eu felis hendrerit tincidunt id sed nulla. Quisque pharetra tincidunt laoreet. In hac habitasse platea dictumst. Cras nec iaculis libero. Suspendisse molestie, orci quis iaculis pulvinar, velit dui fermentum est, vel egestas quam libero nec neque. Proin ut nisl id tellus fringilla porttitor. Mauris vehicula dapibus sem, ac sodales augue vulputate vitae. Ut at libero cursus, hendrerit erat in, iaculis enim.

                            Nulla sed sodales erat, at egestas neque. Ut ut orci quis sem pulvinar convallis. Mauris in leo nec enim dignissim facilisis sit amet id elit. Nulla scelerisque felis finibus risus maximus, nec accumsan justo viverra. In finibus rhoncus vehicula. Vestibulum et sem magna. Vivamus vehicula urna id justo luctus tempus.

                            Donec tincidunt lobortis augue ut posuere. Nam neque odio, rhoncus ac fermentum nec, luctus eu dui. Aenean malesuada risus at nibh accumsan, quis auctor ipsum tempor. Donec felis justo, congue eget fringilla nec, faucibus porta justo. Nullam laoreet elit vitae dolor pharetra vulputate. Vestibulum dictum sit amet mi sed aliquet. Vivamus lacinia nulla sit amet dolor facilisis, ut maximus mauris bibendum. Proin mollis turpis quis tellus mattis, quis sollicitudin lacus egestas. Aenean quam lacus, dapibus dictum gravida tempus, luctus pellentesque lacus. Phasellus rhoncus pulvinar eros vel pharetra. Fusce porta blandit ornare. Donec diam ligula, rutrum et enim quis, consectetur pharetra risus. Mauris dapibus nisl in vehicula molestie. Mauris id vehicula mauris. Nulla sem lacus, pharetra id ex et, auctor laoreet nunc.

                            Quisque bibendum felis nisi, sit amet cursus turpis faucibus sit amet. Curabitur vulputate rutrum vehicula. Nunc turpis ipsum, aliquam in laoreet vitae, fringilla eget neque. Vestibulum eu sodales est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque in feugiat ipsum. Aliquam mollis urna sit amet nibh maximus, non cursus elit viverra. Aenean at arcu tincidunt, tempor lorem eget, consequat nisi. Suspendisse porta ante sit amet magna sagittis, eu mollis orci lacinia. Mauris a augue eget tellus molestie convallis.

                            Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent eget lacus at metus cursus fringilla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed euismod viverra mollis. Aliquam facilisis semper nibh non ultrices. Praesent eleifend neque turpis, eget ultrices erat feugiat at. Vestibulum nec arcu at turpis laoreet lacinia. Morbi purus enim, sagittis quis pharetra ultrices, accumsan quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean eget sapien risus. Sed volutpat, dui sit amet rutrum placerat, neque elit volutpat justo, id lacinia elit erat vitae massa. Pellentesque finibus pretium nulla ac mattis. Morbi molestie a purus sit amet pretium. Suspendisse hendrerit tincidunt ante, quis dictum felis lacinia ac. Praesent tempor urna tellus.

                            Sed sit amet venenatis quam. Nam vestibulum, tortor eget luctus condimentum, lorem tortor cursus massa, non bibendum massa ligula et mauris. Cras at arcu mattis lectus euismod imperdiet ac eu nisi. Etiam malesuada sem nibh, quis elementum nulla tincidunt sed. Nam elementum purus sit amet convallis faucibus. Praesent et velit ac sapien facilisis consequat. Mauris non facilisis mi. Sed lobortis lorem vitae turpis efficitur iaculis. Curabitur id est ac tellus sodales sagittis. Donec vehicula nisi est, ultrices malesuada lacus consequat ut.

                            Nam eu consectetur dolor. Sed pretium ut nulla sed congue. Proin convallis enim metus, vitae sagittis tortor tristique sit amet. Duis sit amet viverra massa, quis ultricies tortor. Aliquam eu dui congue, semper massa sed, feugiat metus. Mauris est nisi, finibus sit amet arcu id, laoreet semper ante. Etiam quis sodales ipsum. Donec sed porta erat. Nullam ac lectus arcu. Suspendisse sem tellus, suscipit ut accumsan vel, dictum vitae nulla. Phasellus fringilla dui aliquam egestas varius. Nunc at neque nunc. Nullam ac eros ornare, laoreet massa eu, porta erat.

                            Fusce eget dolor id velit venenatis varius. Integer velit mauris, luctus eu vehicula eget, congue et diam. Praesent eu luctus lectus, ac congue tortor. Nullam lacinia sapien eget orci lobortis, quis rhoncus ex finibus. Etiam maximus odio sit amet nibh semper hendrerit. Nulla sed pharetra mi. Mauris leo dolor, pulvinar ac tempus vel, semper nec quam. Etiam volutpat lectus vel nunc fermentum, ut tempor erat luctus. Nunc euismod orci nec leo consequat placerat. Praesent suscipit consectetur dolor, in blandit dolor placerat vel.

                            Maecenas posuere libero non molestie lobortis. Sed ut mattis lorem. Donec euismod leo vitae turpis porttitor, id pulvinar tortor imperdiet. Quisque nec felis eu est scelerisque maximus sit amet sed augue. Nam non convallis odio. Donec id lacus non eros ullamcorper rhoncus nec eget lacus. Suspendisse potenti. Curabitur quam velit, finibus eu rutrum ut, tincidunt a leo. Morbi a finibus eros, eu tincidunt enim. Mauris tincidunt euismod leo vitae tincidunt. Sed fringilla, urna sit amet varius malesuada, sapien turpis vestibulum elit, quis sagittis tellus ex at dolor.
                        </Text>
                    </View>
                </ScrollView>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'blue',
    },
    welcome: {
        fontSize: 20,
        textAlign: 'center',
        margin: 10,
    },
    instructions: {
        textAlign: 'center',
        color: '#333333',
        marginBottom: 5,
    },
});
